apiVersion: v1
kind: Service
metadata:
  name: hvac-service
spec:
  selector:
    app: hvac-controller
  ports:
    - protocol: TCP
      port: 80 # Le port sur lequel le service sera exposé
      targetPort: 80 # Le port du conteneur que le service va cibler
  type: ClusterIP # Utilisez LoadBalancer si vous souhaitez exposer le service à l'extérieur du cluster sur un cloud provider
