apiVersion: apps/v1
kind: Deployment
metadata:
  name: hvac-controller
  namespace: grp02eq7-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hvac-controller
  template:
    metadata:
      labels:
        app: hvac-controller
    spec:
      containers:
      - name: hvac-controller
        image: axldev99/etsmtl-log680-oxygencs-eq7:etsmtl-log680-oxygencs-eq7.latest
        resources:
          limits:
            cpu: "0.3"
            memory: "256Mi"
          requests:
            cpu: "50m"
            memory: "128Mi"
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: my-dockerhub-secret
